routes/web.php
<?php

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MemosController;
use App\Http\Controllers\VocabwordController;
use App\Http\Controllers\MemocategsController;
use App\Http\Controllers\ReferencesController;
use App\Models\Vocabword;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::group([
    'middleware' => 'auth',
    'prefix' => 'admin'
], function () {
    /*Route::get('/categs', function ()    {
        dd("here");
    })->name('memocategs.index');*/
    Route::resources([
        'memos'         => MemosController::class,
        'memocategs'    => MemocategsController::class,
        'references'    => ReferencesController::class,
        'vocabwords'    => VocabwordController::class
    ]);
});

Route::get('/', [Controller::class, 'home'])->name('home');

Route::get('/vocabulaire', [VocabwordController::class, 'devine'])->name('vocab.devine');

//Présentation du domaine : le menu de nav permet d'accéder à des catégories
Route::get('/memos/{slugSubDomaine}', [Controller::class, 'subDomaineContent'])->where(['slugSubDomaine' => '[a-z0-9_\-]+'])->name('subdomain.index');

//la même route sert à accéder au détail des catégories et à celui des sous-catégories
Route::get('/memos/{slugSubDomaine}/{slugCateg}', [MemocategsController::class, 'categContent'])->where([
    'slugSubDomaine' => '[a-z0-9_\-]+',
    'slugCateg' => '[a-z0-9_\-]+',
])->name('memocategs.show2');



Route::get('/memos/{subDomain}/{subCateg}/{memo}', [MemosController::class, 'show'])->where([
    'subDomain' => '[a-z0-9_\-]+',
    'subCateg' => '[a-z0-9_\-]+',
    'memo' => '[a-z0-9_\-]+',
])->name('memos.show2');



/*

/*
Route::get('/', function () {
    return view('home');
})->middleware(['auth'])->name('home');*/
/*
Route::resources([
    'memos' => MemosController::class,
    'memocategs' => MemocategsController::class,
]);*//*
Route::middleware('auth')->group(function() {
    Route::resources([
        'references' => ReferencesController::class
    ]);
});

Route::resource('memos', MemosController::class)->parameters([
    ['memos' => 'slug']
]);

/*
Route::resource('memocategs', MemocategsController::class)->parameters([
    ['memocategs' => 'slug']
]);*/

app/Models/Memo.php
<?php

namespace App\Models;

use App\Models\User;
use App\Models\Domaine;
use App\Models\Memocateg;
use App\Models\Reference;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Memo extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'memos';

    /**
    * column in DB used for URLs
    */
    public function getRouteKeyName(){
        return "skey";
    }

    protected $fillable = [
        'id_user',
        'id_memocategs',
        'title',
        'slug',
        'domain', 
        'skey',
        'path',
        'numero',
        'is_public'
    ] ;

    public function getPath() {
        $subDomain = Domaine::where([['slug', '=', $this->domain]])->first() ;
        $parentDomain = Domaine::where([['id', '=', $subDomain->id_domaine_parent]])->first() ;

        $subCateg = Memocateg::where([['id', '=', $this->id_memocategs]])->first() ;
        $parentCateg = Memocateg::where([['id', '=', $subCateg->id_memocategs_parent]])->first() ;

        $path = $parentDomain->slug . "_". $this->domain . DIRECTORY_SEPARATOR. $parentCateg->skey . "_". $subCateg->skey . DIRECTORY_SEPARATOR. $this->path ;
        return $path ;
    }

    /* --------------------- RELATIONS --------------------- */

    /* RELATION ManyMemos To OneUser */
    public function user() { 
        return $this->belongsTo(User::class,'id_user','id'); 
    }

    /* RELATION ManyMemos To OneMemocateg */
    public function memocateg() { 
        return $this->belongsTo(Memocateg::class,'id_memocategs','id'); 
    }

    /* RELATION OneMemo To ManyReferences */
    public function refs() {
        return $this->hasMany(Reference::class, 'id_memo', 'id');
    }
}

app/Http/Controllers/MemosController.php
<?php

namespace App\Http\Controllers;

use App\Models\Memo;
use App\Models\Memocateg;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\StoreMemoRequest;
use App\Http\Requests\UpdateMemoRequest;
use App\Models\Domaine;

class MemosController extends Controller
{
    protected $boolean_fields = [
        'is_public'
    ];

    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
        // $this->middleware('auth')->except(['index', 'show']);
        //TODO
        //$this->middleware('byowner')->only(['edit', 'update', 'destroy]);
    }

    /* *********************************************************************** */

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Support\Facades\View;
     */
    public function index()
    {
        if (is_null(Auth::user())) {
            $memos = Memo::select(['id', 'title', 'id_memocategs'])
                ->where('is_public', 1)
                ->orderBy('numero')
                ->get();

            $categs = Memocateg::where('is_public', 1)
                ->orderBy('numero')
                ->get()
                ->keyBy('id')
                ->toArray();
        } else {
            $memos = Memo::where('id_user', Auth::user()->id)
                ->orWhere('is_public', 1)
                ->orderBy('numero')
                ->get();

            $categs = Memocateg::where('id_user', Auth::user()->id)
                ->orderBy('numero')
                ->get()
                ->keyBy('id')
                ->toArray();
        }

        foreach ($memos as $key => $aMemo) {
            //dd($categs[$aMemo->id_memocategs]);
            if (!array_key_exists('memos', $categs[$aMemo->id_memocategs])) {
                $categs[$aMemo->id_memocategs]['memos'] = [];
            }
            $categs[$aMemo->id_memocategs]['memos'][] = $aMemo;
        }
        $menuContent = Memocateg::where([
            ['domain', "=", $aMemo->domain],
            ['id_memocategs_parent', "=", null],
            ['is_public', "=", 1]
        ])->get()->keyBy('slug')->sortBy('numero');
        
        return view('resources.memos.index', compact('categs', 'menuContent'));
    }

    /* *********************************************************************** */

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Support\Facades\View;
     */
    public function create()
    {
        //$categs = $this->findMemocategs();
        $domains = $this->listDomains();
        $categs = $this->listCategs();

        $memo = new Memo;
        return view('resources.memos.create', compact(['memo', 'categs', 'domains']));
    }

    /* *********************************************************************** */

    /**
     * Store a newly created resource in storage.
     * @param  \App\Http\Requests\StoreMemoRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreMemoRequest $request)
    {
        $validatedData = $request->validated();
        $validatedData['id_user'] = Auth::id();
        $subcateg = Memocateg::findOrFail($validatedData['id_memocategs']) ;
        $validatedData['slug'] = $validatedData['domain'] . "_" .  $subcateg->slug . "_" . $validatedData['skey'] ;
        $validatedData = $this->completeBooleanFields($validatedData);
        $nMemo = Memo::create($validatedData);

        return redirect()->route('memos.index')->with('success', 'Le mémo a bien été ajouté');
    }

    /* *********************************************************************** */

    /**
     * Display the specified resource.

     * @return \Illuminate\Support\Facades\View;
     */
    public function show(string $subDomain, string $subCateg, string $memo)
    {
        $memo = Memo::select('memos.*', 'memocategs.label')->join("memocategs", "memocategs.id", "=", "memos.id_memocategs")
            ->where([["memos.skey", "=", $memo], ['memocategs.slug', "=", $subCateg]])->first();

        if (!is_null($memo) && ($memo->is_public === 1 || (!!Auth::user() && $memo->id_user === Auth::user()->id))) {
            $pCateg = Memocateg::findOrFail($memo->id_memocategs);
            $categs = [
                [
                    'label' => $pCateg->label,
                    'slug'  => $pCateg->slug
                ]
            ];
            if (!is_null($pCateg->id_memocategs_parent)) {
                $pCateg = Memocateg::findOrFail($pCateg->id_memocategs_parent);
                $categs[] = [
                    'label' => $pCateg->label,
                    'slug'  => $pCateg->slug
                ];
            }
            $parentCategs = array_reverse($categs);

            $menuContent = Memocateg::where([
                ['domain', "=", $memo->domain],
                ['id_memocategs_parent', "=", null],
                ['is_public', "=", 1]
            ])->get()->keyBy('slug')->sortBy('numero');
            //dd($memo->getPath());
            return view('resources.memos.show', compact(['memo', 'parentCategs', 'menuContent']));
        } else {
            dd("Woops");
            abort(404);
        }
    }

    /* *********************************************************************** */

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Memo  $memo
     * @return \Illuminate\Support\Facades\View;
     */
    public function edit(Memo $memo)
    {
        $this->rejectIfUserNotOwnerOf($memo);

        //$categs = $this->findMemocategs();
        $categs = $this->listCategs();
        $domains = $this->listDomains();

        $menuContent = Memocateg::where([
            ['domain', "=", $memo->domain],
            ['id_memocategs_parent', "=", null],
            ['is_public', "=", 1]
        ])->get()->keyBy('slug')->sortBy('numero');
        
        return view('resources.memos.edit', compact(['memo', 'categs', 'domains', 'menuContent']));
    }

    /* *********************************************************************** */

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateMemoRequest  $request
     * @param  \App\Models\Memo  $memo
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateMemoRequest $request, Memo $memo)
    {
        $this->rejectIfUserNotOwnerOf($memo);

        $validatedData = $request->validated();
        $validatedData = $this->completeBooleanFields($validatedData);

        $memo->update($validatedData);

        return redirect()->route('memos.show2', [
            'subDomain' => $memo->domain,
            'subCateg' => $memo->memocateg->slug,
            'memo' => $memo->skey
        ])->with('success', 'Le mémo a bien été modifié');
    }

    /* *********************************************************************** */

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Memo  $memo
     * @return \Illuminate\Http\Response
     */
    public function destroy(Memo $memo)
    {
        $this->rejectIfUserNotOwnerOf($memo);

        $memo->delete();

        return redirect()->route('memos.index')->with('success', 'Le mémo a bien été supprimé');
    }

    /* *********************************************************************** */

    protected function rejectIfUserNotOwnerOf($object)
    {
        if (Auth::user()->id !== $object->id_user) {
            abort(401);
        }
    }

    //TODO  only public or owned by user
    protected function listDomains()
    {
        $domains = Domaine::whereNull('id_domaine_parent')->get();

        $domainsAndSub = [];

        return $domains;
    }
    protected function listCategs()
    {
        $allCategs = Memocateg::whereNull('id_memocategs_parent')->get();
        $categsByDomainSlug = [];



        return $allCategs;
    }

    protected function completeBooleanFields(array $validatedData)
    {
        foreach ($this->boolean_fields as $aField) {
            if (!array_key_exists($aField, $validatedData)) {
                $validatedData[$aField] = 0;
            }
        }
        return $validatedData;
    }

    /*protected function findMemocategs() {
        $parentCategs = Memocateg::select(['id', 'label'])
            ->where([
                ['is_public', 1],
                ['id_memocategs_parent', null]
            ])->orWhere([
                ['id_user', Auth::user()->id],
                ['id_memocategs_parent', null]
            ])->orderBy('numero')
            ->get()->keyBy('id');
        //$parentCategsIds = $parentCategs->keys()->toArray() ;
        $categs = $parentCategs->toArray() ;
                 
        //TODO ne prendre que celles dans les id des parents
        $subCategs = Memocateg::select(['id', 'label', 'id_memocategs_parent', 'numero'])
            ->where([
                ['is_public', 1],
                ['id_memocategs_parent', '<>', NULL]
            ])->orWhere([
                ['id_user', Auth::user()->id],
                ['id_memocategs_parent', '<>', NULL]
            ])->orderBy('numero')
            ->get()->toArray();

        foreach ($subCategs as $key => $aSubCateg) {
            if(!array_key_exists('subcategs', $categs[$aSubCateg['id_memocategs_parent']])) {
                $categs[$aSubCateg['id_memocategs_parent']]['subcategs'] = [] ;
            }
            $categs[$aSubCateg['id_memocategs_parent']]['subcategs'][$aSubCateg['numero']] = $aSubCateg ;
        }

        return $categs ;
    }*/
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/resources/memos/_form.blade.php
<form
    action="@if($method === 'PUT'){{ route('memos.update', ['memo' => $memo->skey]) }}@else{{ route('memos.store')}}@endif" method="post">

    @csrf
    @if($method === 'PUT')
        @method('PUT')
    @endif
    
    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="title" required>Titre</label>
        </div>
        <div class="form_col-75">
            <input id="title" name="title" type="text" value="{{ $memo->title }}"
                class="form-input @error('title') is-invalid @enderror" maxlength="255" required />
        </div>
        @error('title')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="slug" required>SKey</label>
        </div>
        <div class="form_col-75">
            <input id="skey" name="skey" type="text" value="{{ $memo->skey }}"
                class="form-input @error('skey') is-invalid @enderror" maxlength="255" required />
        </div>
        @error('skey')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="domain" required>Sous-domaine</label>
        </div>
        <div class="form_col-75"><select name="domain" id="domain">
            <option></option>
            @foreach ($domains as $item)
                <optgroup label="{{ $item->label}}">
                    @foreach ($item->childrenDomaines as $subD)
                        <option {{ $subD->slug === $memo->domain ? 'selected' : '' }} value="{{ $subD->slug }}">{{ $subD->label }}</option>
                    @endforeach
                    
                </optgroup>
            @endforeach
            </select></div>
        @error('domain')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="id_memocategs" required>Sous-catégorie</label>
        </div>
        <div class="form_col-75"><select name="id_memocategs" id="id_memocategs">
            <option></option>
            @foreach ($categs as $item)
                <optgroup label="{{ $item->label}}">
                    @foreach ($item->childrenCategs as $subC)
                        <option {{ $subC->id === $memo->id_memocategs ? 'selected' : '' }} value="{{ $subC->id }}">{{ $subC->label }}</option>
                    @endforeach
                    
                </optgroup>
            @endforeach
            </select></div>
        @error('id_memocategs')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="path" required>Nom de fichier (sans l'extension)</label>
        </div>
        <div class="form_col-75">
            <input id="path" name="path" type="text" value="{{ $memo->path }}"
                class="form-input @error('path') is-invalid @enderror" maxlength="255" required placeholder="00_nomFichierSansExt" />
        </div>
        @error('path')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25"><label for="numero" required>Ordre (numéro)</label></div>
        <div class="form_col-75"><input id="numero" name="numero" value="{{ $memo->numero }}" type="number"
                class="form-input" required /></div>
        @error('numero')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25"></div>
        <div class="form_col-75">
            <input type="checkbox" name="is_public" {{ $memo->is_public === 1 ? 'checked' : '' }} id="is_public" value="1" />
            <label for="is_public">Visibilité publique</label></div>
        @error('is_public')
            {{ $message }}
        @enderror
    </div>


    <input class="button validation" type="submit" value="Envoyer" />
</form>

resources/views/resources/memos/create.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => [],
        ])
    </x-slot>

    <x-slot name="header">
        <h1 class="font-semibold text-xl leading-tight">
            Ajouter un nouveau mémo
        </h1>
    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @include('resources.memos._form',
            [
                'method' => 'post'
            ])
        </div>
    </div>
</x-app-layout>

resources/views/resources/memos/edit.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => $menuContent,
        ])
    </x-slot>
    
    <x-slot name="header">
        <h1 class="font-semibold text-xl leading-tight">
            Modification de "{{ $memo->title }}"
        </h1>
        <form method="POST" action="{{ route('memos.destroy', $memo) }}">
            @csrf
            @method('DELETE')
            <button class="button dangerous" type="submit">Supprimer</button>
        </form>
    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @include('resources.memos._form',
                [
                    'method' => 'PUT'
                ]
            )
        </div>
    </div>
</x-app-layout>

resources/views/resources/memos/index.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => [],
        ])
    </x-slot>

    <x-slot name="header">
        <h1 class="font-semibold text-xl leading-tight">
            {{ __('Liste des Mémos') }}
        </h1>
        @if(Auth::user() !== null)
            <a href="{{ route('memos.create') }}">Ajouter</a>
        @endif
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @foreach ($categs as $aCateg)
                @isset($aCateg['memos'])
                    <section class="mb-4">
                        <h2>{{ $aCateg['label'] }}</h2>
                        <ul>
                            @foreach ($aCateg['memos'] as $aMemo)
                                <li class="{{ $aMemo->is_public === 0 ? 'is_private' : '' }}"><a href="{{ route('memos.show2', ['subDomain' => $aMemo->domain, 'subCateg' => $aMemo->memocateg->slug, 'memo' => $aMemo->skey]) }}">{{ $aMemo->title }}</a></li>
                            @endforeach
                        </ul>
                    </section>
                @endisset
            @endforeach
        </div>
    </div>
</x-app-layout>

resources/views/resources/memos/show.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => $menuContent,
        ])
    </x-slot>
    
    <x-slot name="header">
        <nav class="ariane">
            <a href="{{ route('memocategs.show2', ['slugSubDomaine' => $memo->domain, 'slugCateg' => $parentCategs[0]['slug']]) }}"> {{ $parentCategs[0]['label'] }}</a> > 
            <a href="{{ route('memocategs.show2', ['slugSubDomaine' => $memo->domain, 'slugCateg' =>$parentCategs[1]['slug']]) }}"> {{ $parentCategs[1]['label'] }}</a>
        </nav>

        <div class="d-flex justify-between items-center">
            <h1 class="font-semibold text-xl leading-tight">
                {{ $memo->title }}
            </h1>
            @if (Auth::user() !== null && $memo->id_user === Auth::user()->id)
                <a class="button" href="{{ route('memos.edit', ['memo' => $memo->skey]) }}">Modifier</a>
            @endif
        </div>

        @if ($memo->is_public === 0)
            <p class="text-warning">Ce mémo privé n'est visible que par vous</p>
        @endif
    </x-slot>

    <aside class="py-6">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <span class="txt_catchy">Sommaire cliquable</span>
            <ul id="summary"></ul>
        </div>
    </aside>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @include('memos.' . $memo->getPath()) 
        </div>
    </div>

    @if (count($memo->refs) > 0 || Auth::user() )
    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <h2>Ressources disponibles</h2>
            @auth
                <a href="{{ route('references.create', ['id_memo' => $memo->id]) }}" target="_blank" rel="noopener noreferrer">Ajouter</a>
            @endauth

            @include('resources.references._listing',
            [
                'references' => $memo->refs
            ]
        )
        </div>
    </div>        
    @endif
    
</x-app-layout>