routes/web.php
<?php

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MemosController;
use App\Http\Controllers\VocabwordController;
use App\Http\Controllers\MemocategsController;
use App\Http\Controllers\ReferencesController;
use App\Models\Vocabword;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::group([
    'middleware' => 'auth',
    'prefix' => 'admin'
], function () {
    /*Route::get('/categs', function ()    {
        dd("here");
    })->name('memocategs.index');*/
    Route::resources([
        'memos'         => MemosController::class,
        'memocategs'    => MemocategsController::class,
        'references'    => ReferencesController::class,
        'vocabwords'    => VocabwordController::class
    ]);
});

Route::get('/', [Controller::class, 'home'])->name('home');

Route::get('/vocabulaire', [VocabwordController::class, 'devine'])->name('vocab.devine');

//Présentation du domaine : le menu de nav permet d'accéder à des catégories
Route::get('/memos/{slugSubDomaine}', [Controller::class, 'subDomaineContent'])->where(['slugSubDomaine' => '[a-z0-9_\-]+'])->name('subdomain.index');

//la même route sert à accéder au détail des catégories et à celui des sous-catégories
Route::get('/memos/{slugSubDomaine}/{slugCateg}', [MemocategsController::class, 'categContent'])->where([
    'slugSubDomaine' => '[a-z0-9_\-]+',
    'slugCateg' => '[a-z0-9_\-]+',
])->name('memocategs.show2');



Route::get('/memos/{subDomain}/{subCateg}/{memo}', [MemosController::class, 'show'])->where([
    'subDomain' => '[a-z0-9_\-]+',
    'subCateg' => '[a-z0-9_\-]+',
    'memo' => '[a-z0-9_\-]+',
])->name('memos.show2');



/*

/*
Route::get('/', function () {
    return view('home');
})->middleware(['auth'])->name('home');*/
/*
Route::resources([
    'memos' => MemosController::class,
    'memocategs' => MemocategsController::class,
]);*//*
Route::middleware('auth')->group(function() {
    Route::resources([
        'references' => ReferencesController::class
    ]);
});

Route::resource('memos', MemosController::class)->parameters([
    ['memos' => 'slug']
]);

/*
Route::resource('memocategs', MemocategsController::class)->parameters([
    ['memocategs' => 'slug']
]);*/

app/Models/Reference.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Reference extends Model
{
    use HasFactory;

    protected $fillable = [
        'id_user',
        'id_memocateg',
        'id_memo',
        'label',
        'url',
        'path_capture',
        'is_rss',
        'is_veille',
        'is_public',
        //'created_at',
        //'updated_at',
        //'deleted_at'
    ] ;

    /**
     * The model's default values for attributes.
     *
     * @var array
     */
    protected $attributes = [
        'id_memocateg'=> null,
        'id_memo'=> null,
        'is_rss'=> false,
        'is_veille'=> false,
        'is_public'=> true
    ];
}

app/Http/Controllers/ReferencesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Reference;
use GuzzleHttp\Psr7\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\StoreReferenceRequest;
use App\Http\Requests\UpdateReferenceRequest;

class ReferencesController extends Controller
{
    protected $boolean_fields = [
        'is_rss',
        'is_veille',
        'is_public'
    ] ;
    
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct() {
        parent::__construct();
        $this->middleware('auth')->except(['index']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (is_null(Auth::user())) {
            $references = Reference::where('is_public', 1)->get();
        }
        else {
            $references = Reference::all();
        }

        $menuContent = [] ;

        return view('resources.references.index', compact('references', 'menuContent'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $ref = new Reference;
        if(array_key_exists('id_memo', $_GET)) {
            $ref->id_memo = (int) $_GET['id_memo'] ;
        }
        if(array_key_exists('id_memocateg', $_GET)) {
            $ref->id_memocateg = (int) $_GET['id_memocateg'] ;
        }

        $menuContent = [] ;

        return view('resources.references.create', compact(['ref', 'menuContent'])) ;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreReferenceRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreReferenceRequest $request)
    {
        $validatedData = $request->validated();
        $validatedData['id_user'] = Auth::id();
        $validatedData = $this->completeBooleanFields($validatedData) ;
                
        $nRef = Reference::create($validatedData);

        return redirect()->route('references.index')->with('success', 'La référence a bien été ajoutée');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Reference  $reference
     * @return \Illuminate\Http\Response
     */
    public function edit(Reference $reference)
    {
        $this->rejectIfUserNotOwnerOf($reference) ;

        $ref = $reference ;

        $menuContent = [] ;

        return view('resources.references.edit', compact(['ref', 'menuContent'])) ;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateReferenceRequest  $request
     * @param  \App\Models\Reference  $reference
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateReferenceRequest $request, Reference $reference)
    {
        $this->rejectIfUserNotOwnerOf($reference) ;

        $validatedData = $request->validated();
        $validatedData = $this->completeBooleanFields($validatedData) ;

        $reference->update($validatedData);

        return redirect()->route('references.index')->with('success', 'La référence a bien été modifiée');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Reference  $reference
     * @return \Illuminate\Http\Response
     */
    public function destroy(Reference $reference)
    {
        $this->rejectIfUserNotOwnerOf($reference) ;

        $reference->delete() ;

        return redirect()->route('references.index')->with('success', 'La référence a bien été supprimée');
    }

    /* *********************************************************************** */

    protected function rejectIfUserNotOwnerOf($object)
    {
        if (Auth::user()->id !== $object->id_user) {
            abort(401);
        }
    }

    protected function completeBooleanFields(array $validatedData) {
        foreach($this->boolean_fields as $aField) {
            if(!array_key_exists($aField, $validatedData)) {
                $validatedData[$aField] = 0 ;
            }
        }
        return $validatedData ;
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/resources/references/_form.blade.php
<form
    action="@if($method === 'PUT'){{ route('references.update', ['reference' => $ref->id]) }}@else{{ route('references.store')}}@endif" method="post">

    @csrf
    @if($method === 'PUT')
        @method('PUT')
    @endif
    
    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="label" required>Titre</label>
        </div>
        <div class="form_col-75">
            <input id="label" name="label" type="text" value="{{ $ref->label }}"
                class="form-input @error('label') is-invalid @enderror" maxlength="255" required />
        </div>
        @error('label')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="url">Url</label>
        </div>
        <div class="form_col-75">
            <input id="url" name="url" type="text" value="{{ $ref->url }}"
                class="form-input @error('url') is-invalid @enderror" maxlength="255" />
        </div>
        @error('url')
            {{ $message }}
        @enderror
    </div>

    <fieldset>
        <legend required>Rattachement</legend>
        <p>De préférence à une seule chose parmi catégorie ou mémo…</p>

        <div class="form_row mb-4">
            <div class="form_col-25"><label for="id_memocateg">Id de la catégorie</label></div>
            <div class="form_col-75"><input id="id_memocateg" name="id_memocateg" value="{{ $ref->id_memocateg }}" type="number"
                    class="form-input" /></div>
            @error('id_memocateg')
                {{ $message }}
            @enderror
        </div>
    
        <div class="form_row mb-4">
            <div class="form_col-25"><label for="id_memo">ID du mémo</label></div>
            <div class="form_col-75"><input id="id_memo" name="id_memo" value="{{ $ref->id_memo }}" type="number"
                    class="form-input" /></div>
            @error('id_memo')
                {{ $message }}
            @enderror
        </div>
    </fieldset>
    

    <div class="form_row mb-4">
        <div class="form_col-25"></div>
        <div class="form_col-75">
            <input type="checkbox" name="is_rss" {{ $ref->is_rss === 1 ? 'checked' : '' }} id="is_rss" value="1" />
            <label for="is_rss">Flux RSS</label></div>
        @error('is_rss')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25"></div>
        <div class="form_col-75">
            <input type="checkbox" name="is_veille" {{ $ref->is_veille === 1 ? 'checked' : '' }} id="is_veille" value="1" />
            <label for="is_veille">Site pour Veille</label></div>
        @error('is_veille')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25"></div>
        <div class="form_col-75">
            <input type="checkbox" name="is_public" {{ $ref->is_public === 1 ? 'checked' : '' }} id="is_public" value="1" />
            <label for="is_public">Visibilité publique</label></div>
        @error('is_public')
            {{ $message }}
        @enderror
    </div>

    <input class="button validation" type="submit" value="Envoyer" />
</form>

resources/views/resources/references/_listing.blade.php
<ul>
    @foreach ($references as $aRef)
        <li>
            @if(!is_null($aRef->url))
                <a href="{{ $aRef->url }}" target="_blank" rel="noopener noreferrer">{{ $aRef->label }}</a>
            @else
                {{ $aRef->label }}
            @endif
            @auth
            <a href="{{ route('references.edit', $aRef->id) }}" target="_blank" rel="noopener noreferrer">Modifier</a>
            @endauth
        </li>
    @endforeach
</ul>

resources/views/resources/references/create.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => [],
        ])
    </x-slot>

    <x-slot name="header">
        <h1 class="font-semibold text-xl leading-tight">
            Ajouter une référence
        </h1>
    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @include('resources.references._form',
            [
                'method' => 'post'
            ])
        </div>
    </div>
</x-app-layout>

resources/views/resources/references/edit.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => [],
        ])
    </x-slot>
    
    <x-slot name="header">
        <h1 class="font-semibold text-xl leading-tight">
            Modification d'une référence
        </h1>
        <form method="POST" action="{{ route('references.destroy', $ref) }}">
            @csrf
            @method('DELETE')
            <button class="button dangerous" type="submit">Supprimer</button>
        </form>

    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @include('resources.references._form',
                [
                    'method' => 'PUT'
                ]
            )
        </div>
    </div>
</x-app-layout>

resources/views/resources/references/index.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => [],
        ])
    </x-slot>

    <x-slot name="header">
        <h1 class="font-semibold text-xl leading-tight">
            {{ __('Liste des Références') }}
        </h1>

        @auth
            <a href="{{ route('references.create') }}">Ajouter</a>
        @endauth 
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if (count($references) === 0 )
            <p>Aucune référence n'est disponible en base de données pour votre statut actuellement.</p>
            @else
                @include('resources.references._listing',
                    [
                        'references' => $references
                    ]
                )
            @endif
        </div>
    </div>
</x-app-layout>