routes/web.php
<?php

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\MemosController;
use App\Http\Controllers\VocabwordController;
use App\Http\Controllers\MemocategsController;
use App\Http\Controllers\ReferencesController;
use App\Models\Vocabword;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require __DIR__ . '/auth.php';

Route::group([
    'middleware' => 'auth',
    'prefix' => 'admin'
], function () {
    /*Route::get('/categs', function ()    {
        dd("here");
    })->name('memocategs.index');*/
    Route::resources([
        'memos'         => MemosController::class,
        'memocategs'    => MemocategsController::class,
        'references'    => ReferencesController::class,
        'vocabwords'    => VocabwordController::class
    ]);
});

Route::get('/', [Controller::class, 'home'])->name('home');

Route::get('/vocabulaire', [VocabwordController::class, 'devine'])->name('vocab.devine');

//Présentation du domaine : le menu de nav permet d'accéder à des catégories
Route::get('/memos/{slugSubDomaine}', [Controller::class, 'subDomaineContent'])->where(['slugSubDomaine' => '[a-z0-9_\-]+'])->name('subdomain.index');

//la même route sert à accéder au détail des catégories et à celui des sous-catégories
Route::get('/memos/{slugSubDomaine}/{slugCateg}', [MemocategsController::class, 'categContent'])->where([
    'slugSubDomaine' => '[a-z0-9_\-]+',
    'slugCateg' => '[a-z0-9_\-]+',
])->name('memocategs.show2');



Route::get('/memos/{subDomain}/{subCateg}/{memo}', [MemosController::class, 'show'])->where([
    'subDomain' => '[a-z0-9_\-]+',
    'subCateg' => '[a-z0-9_\-]+',
    'memo' => '[a-z0-9_\-]+',
])->name('memos.show2');



/*

/*
Route::get('/', function () {
    return view('home');
})->middleware(['auth'])->name('home');*/
/*
Route::resources([
    'memos' => MemosController::class,
    'memocategs' => MemocategsController::class,
]);*//*
Route::middleware('auth')->group(function() {
    Route::resources([
        'references' => ReferencesController::class
    ]);
});

Route::resource('memos', MemosController::class)->parameters([
    ['memos' => 'slug']
]);

/*
Route::resource('memocategs', MemocategsController::class)->parameters([
    ['memocategs' => 'slug']
]);*/

app/Models/Memocateg.php
<?php

namespace App\Models;

use App\Models\Memo;
use App\Models\Reference;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Memocateg extends Model
{
    use HasFactory;
    
    /**
    * The table associated with the model.
    *
    * @var string
    */
   protected $table = 'memocategs';

   protected $fillable = [
    'id_user',
    'id_memocategs_parent',
    'label',
    'slug',
    'skey',
    'domain',
    'path',
    'numero',
    'is_public'
] ;

    /**
     * The model's default values for attributes.
     *
     * @var array
     */
    protected $attributes = [
        'id_memocategs_parent'=> null,
        'is_public'=> true
    ];

   /**
    * column in DB used for URLs
    */
    public function getRouteKeyName(){
        return "slug";
    }


    /* --------------------- RELATIONS --------------------- */

    /* RELATION ManyMemocategs To OneUser */
    public function user() { 
        return $this->belongsTo('User::class','id_user','id'); 
    }

    /* RELATION ManyMemocategChild To OneMemocategParent */
    public function parentMemocateg() { 
        return $this->belongsTo('Memocateg::class','id_memocategs_parent','id'); 
    }

    /* RELATION OneMemocateg To ManyMemos */
    public function memos() {
        return $this->hasMany(Memo::class, 'id_memocategs', 'id')->orderBy('numero');
    }

    /* RELATION OneMemocateg To ManyMemocategs */
    public function childrenCategs() {
        return $this->hasMany(Memocateg::class, 'id_memocategs_parent', 'id')->orderBy('numero');
    }

    /* RELATION OneMemocateg To ManyReferences */
    public function refs() {
        return $this->hasMany(Reference::class, 'id_memocateg', 'id');
    }

    
}

app/Http/Controllers/MemocategsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Memocateg;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\StoreMemocategsRequest;
use App\Http\Requests\UpdateMemocategsRequest;
use App\Models\Domaine;
use App\Models\Memo;

class MemocategsController extends Controller
{
    protected $boolean_fields = [
        'is_public'
    ];

    public function __construct()
    {
        parent::__construct();
        //$this->middleware('auth')->except(['index', 'show']);
    }

    public function categContent(string $slugSubDomaine, string $slugSubCateg)
    {
        //TODO le problème d'ici, c'est qu'on récup les categs publiques, mais que dans leur memos() il y a les privés... du coup les mémos privés se listent, bien qu'inaccessibles
        if (is_null(Auth::user())) {
            $data = Memocateg::with(['childrenCategs' => function ($query) {
                $query->where('is_public', 1);
            }])
            ->where([
                ['is_public', "=", 1],
                ['slug', "=", $slugSubCateg]
            ])
            ->orderBy('numero', 'ASC')
            ->firstOrFail();
        } else {
            $data = Memocateg::with(['childrenCategs' => function ($query) {
                $query->where('is_public', 1)
                    ->orWhere('id_user', Auth::user()->id);
            }])
            ->where([
                ['is_public', "=", 1],
                ['slug', "=", $slugSubCateg]
            ])
            ->orWhere([
                ['id_user', "=", Auth::user()->id],
                ['slug', "=", $slugSubCateg]
            ])
            ->orderBy('numero', 'ASC')
            ->firstOrFail();
        }

        /*
        if (is_null(Auth::user())) {
            $data = Memocateg::where([
                ['is_public', "=",  1],
                ['domain', "=", $slugSubDomaine]
                //['id_memocategs_parent', '<=>', null]
            ])
                ->orderBy('numero', 'ASC')
                ->get();
            dd($data);
        } else {
            $data = Memocateg::where([
                ['is_public', 1],
                ['id_memocategs_parent', '=', null]
            ])
                ->orWhere([
                    ['id_user', Auth::user()->id],
                    ['id_memocategs_parent', '=', null]
                ])
                ->orderBy('numero', 'ASC')
                ->get();
        }*/
        $menuContent = Memocateg::where([
            ['domain', "=", $slugSubDomaine],
            ['id_memocategs_parent', "=", null],
            ['is_public', "=", 1]
        ])->get()->keyBy('slug')->sortBy('numero');
       // dd($menuContent);
        return view('resources.memocategs.index2', compact('menuContent', 'data'));
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (is_null(Auth::user())) {
            /*$data = Memocateg::where([
                ['is_public', 1],
                ['id_memocategs_parent', '<=>', null]
            ])
                ->orderBy('numero', 'ASC')
                ->get();*/
            dd('unauthorized');
        } else {
            $parentDomaines/*ById*/ = Domaine::where([['id_domaine_parent', "=", null]])->orderBy('numero', 'ASC')->get()/*->keyBy('id')->toArray()*/;
            //dd($parentDomaines);
            /*$childrenDomains = Domaine::orderBy('numero', 'ASC')->get()->keyBy('id_domaine_parent')->toArray();
            foreach($childrenDomains as $parentId => $aGroupOfChildren) {
                $parentDomainesById[$parentId]['childrenDomains'] = $aGroupOfChildren ;
            }
                dd($parentDomainesById);
*/
            $data = Memocateg::where([
                ['is_public', 1],
                ['id_memocategs_parent', '=', null]
            ])
                ->orWhere([
                    ['id_user', Auth::user()->id],
                    ['id_memocategs_parent', '=', null]
                ])
                ->orderBy('numero', 'ASC')
                ->get();
        }

        return view('resources.memocategs.index', compact('parentDomaines', 'data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $domaines = Domaine::whereNull('id_domaine_parent')->get();
        $memocateg = new Memocateg;
        $parentCategs = Memocateg::whereNull('id_memocategs_parent')->get();
        return view('resources.memocategs.create', compact(['domaines', 'memocateg', 'parentCategs']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreMemocategsRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreMemocategsRequest $request)
    {
        $validatedData = $request->validated();
        $validatedData['id_user'] = Auth::id();
        $validatedData = $this->completeBooleanFields($validatedData);

        $nCateg = Memocateg::create($validatedData);

        return redirect()->route('memocategs.index')->with('success', 'La catégorie a bien été ajoutée');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Memocateg  $memocateg
     * @return \Illuminate\Http\Response
     */
    public function show(Memocateg $memocateg)
    {
        if ($memocateg->is_public !== 1 && (!!Auth::user() && $memocateg->id_user !== Auth::user()->id)) {
            abort(404);
        } else {

            $categ = Memocateg::find($memocateg->id);
            //TODO peut-être besoin d'un menu ?

            $menuContent = Memocateg::where([
                ['domain', "=", $categ->domain],
                ['id_memocategs_parent', "=", null],
                ['is_public', "=", 1]
            ])->get()->keyBy('slug')->sortBy('numero');

            return view('resources.memocategs.show', compact('categ', 'menuContent'));
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Memocateg  $memocateg
     * @return \Illuminate\Http\Response
     */
    public function edit(Memocateg $memocateg)
    {
        $this->rejectIfUserNotOwnerOf($memocateg);

        $domaines = Domaine::whereNull('id_domaine_parent')->get();

        $parentCategs = Memocateg::whereNull('id_memocategs_parent')->get();
        return view('resources.memocategs.edit', compact(['domaines', 'memocateg', 'parentCategs']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateMemocategsRequest  $request
     * @param  \App\Models\Memocateg  $memocateg
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateMemocategsRequest $request, Memocateg $memocateg)
    {
        $this->rejectIfUserNotOwnerOf($memocateg);

        $validatedData = $request->validated();
        $validatedData = $this->completeBooleanFields($validatedData);

        $memocateg->update($validatedData);

        return redirect()->route('memocategs.show', $memocateg->slug)->with('success', 'La catégorie a bien été modifiée');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Memocateg  $memocateg
     * @return \Illuminate\Http\Response
     */
    public function destroy(Memocateg $memocateg)
    {
        $this->rejectIfUserNotOwnerOf($memocateg);

        $memocateg->delete();

        return redirect()->route('memocategs.index')->with('success', 'La catégorie a bien été supprimée');
    }

    /* *********************************************************************** */

    protected function rejectIfUserNotOwnerOf($object)
    {
        if (Auth::user()->id !== $object->id_user) {
            abort(401);
        }
    }

    protected function completeBooleanFields(array $validatedData)
    {
        foreach ($this->boolean_fields as $aField) {
            if (!array_key_exists($aField, $validatedData)) {
                $validatedData[$aField] = 0;
            }
        }
        return $validatedData;
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/resources/memocategs/_form.blade.php
<form
    action="@if ($method === 'PUT') {{ route('memocategs.update', ['memocateg' => $memocateg->slug]) }}@else{{ route('memocategs.store') }} @endif"
    method="post">

    @csrf
    @if ($method === 'PUT')
        @method('PUT')
    @endif

    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="label" required>Label</label>
        </div>
        <div class="form_col-75">
            <input id="label" name="label" type="text" value="{{ $memocateg->label }}"
                class="form-input @error('label') is-invalid @enderror" maxlength="255" required />
        </div>
        @error('label')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="slug" required>Slug</label>
        </div>
        <div class="form_col-75">
            <input id="slug" name="slug" type="text" value="{{ $memocateg->slug }}"
                class="form-input @error('slug') is-invalid @enderror" maxlength="255" required />
        </div>
        @error('slug')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="slug" required>SKey</label>
        </div>
        <div class="form_col-75">
            <input id="skey" name="skey" type="text" value="{{ $memocateg->skey }}"
                class="form-input @error('skey') is-invalid @enderror" maxlength="255" required />
        </div>
        @error('skey')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="domain" required>Sous-Domaine</label>
        </div>

        <div class="form_col-75"><select name="domain" id="domain">
                <option></option>
                @foreach ($domaines as $aParentDomaine)
                    <optgroup label="{{ $aParentDomaine->label }}">
                        @foreach ($aParentDomaine->childrenDomaines as $aSubDomain)
                            <option {{ $memocateg->domain === $aSubDomain->slug ? 'selected' : '' }}
                                value="{{ $aSubDomain->slug }}">{{ $aSubDomain->label }}</option>
                        @endforeach
                    </optgroup>
                @endforeach
            </select>
        </div>
        @error('domain')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="id_memocategs_parent">Catégorie parente éventuelle</label>
        </div>
        <div class="form_col-75"><select name="id_memocategs_parent" id="id_memocategs_parent">
                <option></option>
                @foreach ($parentCategs as $aParentCateg)
                    <option {{ $aParentCateg->id === $memocateg->id_memocategs_parent ? 'selected' : '' }}
                        value="{{ $aParentCateg->id }}">{{ $aParentCateg->label }}</option>
                @endforeach
            </select>
        </div>
        @error('id_memocategs_parent')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25">
            <label for="path" required>Nom de dossier</label>
        </div>
        <div class="form_col-75">
            <input id="path" name="path" type="text" value="{{ $memocateg->path }}"
                class="form-input @error('path') is-invalid @enderror" maxlength="255" required />
        </div>
        @error('path')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25"><label for="numero" required>Ordre (numéro)</label></div>
        <div class="form_col-75"><input id="numero" name="numero" value="{{ $memocateg->numero }}" type="number"
                class="form-input" required /></div>
        @error('numero')
            {{ $message }}
        @enderror
    </div>

    <div class="form_row mb-4">
        <div class="form_col-25"></div>
        <div class="form_col-75">
            <input type="checkbox" name="is_public" {{ $memocateg->is_public === 1 ? 'checked' : '' }} id="is_public"
                value="1" />
            <label for="is_public">Visibilité publique</label>
        </div>
        @error('is_public')
            {{ $message }}
        @enderror
    </div>


    <input class="button validation" type="submit" value="Envoyer" />
</form>

resources/views/resources/memocategs/create.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => [],
        ])
    </x-slot>

    <x-slot name="header">
        <h1 class="font-semibold text-xl leading-tight">
            Ajouter une catégorie de mémo
        </h1>
    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @include('resources.memocategs._form',
            [
                'method' => 'post'
            ])
        </div>
    </div>
</x-app-layout>

resources/views/resources/memocategs/edit.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => [],
        ])
    </x-slot>

    <x-slot name="header">
        <h1 class="font-semibold text-xl leading-tight">
            Modification de "{{ $memocateg->label }}"
        </h1>
        <form method="POST" action="{{ route('memocategs.destroy', $memocateg) }}">
            @csrf
            @method('DELETE')
            <button class="button dangerous" type="submit">Supprimer</button>
        </form>

    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @include('resources.memocategs._form',
                [
                    'method' => 'PUT'
                ]
            )
        </div>
    </div>
</x-app-layout>

resources/views/resources/memocategs/index.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => [],
        ])
    </x-slot>


    <x-slot name="header">
        <h1 class="font-semibold text-xl leading-tight">
            {{ __('Liste des Catégories de mémos') }}
        </h1>
        @auth
            <a href="{{ route('memocategs.create') }}">Ajouter</a>
        @endauth
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @foreach ($parentDomaines as $aDomaine)
            <h2>{{ $aDomaine->label }}</h2>
            @foreach ($aDomaine->childrenDomaines as $aChildDomain)
                <section>
                    <h3>{{ $aChildDomain->label }}</h3>
                    @foreach ($aChildDomain->parentCategs as $aParentCateg)
                        <section>
                            <h4><a href="{{ route('memocategs.show', $aParentCateg->slug) }}" title="id {{ $aParentCateg->id }}">{{ $aParentCateg->label }}</a></h4>
                            @foreach ($aParentCateg->childrenCategs as $aChildCateg)
                            <section>
                                <h5><a href="{{ route('memocategs.show', $aChildCateg->slug) }}" title="id {{ $aChildCateg->id }}">{{ $aChildCateg->label }}</a></h5>
                            </section>
                        @endforeach
                        </section>
                    @endforeach
                </section>
            @endforeach
            @endforeach
        </div>
    </div>
</x-app-layout>

resources/views/resources/memocategs/index2.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => $menuContent,
        ])
    </x-slot>

    <x-slot name="header">
        <h1 class="font-semibold text-xl leading-tight">
            {{ $data->label }}
        </h1>
        @auth
            <a href="{{ route('memos.create') }}">Ajouter</a>
        @endauth
    </x-slot>

    <div class="pt-4 pb-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            @if (str_starts_with($data->slug, 'lang_'))
            <a href="{{ route('vocab.devine') }}">Flashcards de vocabulaire</a>
            @endif

            {{-- Si on est dans une catégorie qui a des sous-categs : on les liste --}}
            @foreach ($data->childrenCategs as $key => $aSubCateg)
                <section class="mb-4">
                    <h2><a href="{{ route('memocategs.show2', ['slugSubDomaine' => $aSubCateg->domain, 'slugCateg' => $aSubCateg->slug]) }}"
                                title="id : {{ $aSubCateg->id }}">{{ $aSubCateg->label }}</a> <span class="text-small"></span>
                        </h2>
                        <ul>
                            @foreach ($aSubCateg->memos as $subKey => $aMemo)
                                @if ($aMemo->is_public === 1 || (Auth::user() && $aMemo->id_user === Auth::user()->id))
                                    <li class="{{ $aMemo->is_public === 0 ? 'is_private' : '' }}"><a
                                            href="{{ route('memos.show2', ['subDomain' => $aSubCateg->domain, 'subCateg' => $aSubCateg->slug, 'memo' => $aMemo->skey]) }}">{{ $aMemo->title }}</a>
                                    </li>
                                @endif
                            @endforeach
                        </ul>
                </section>
            @endforeach

            {{-- Si on est dans une sous-categ : on en liste les mémos --}}
            <ul>
                @foreach ($data->memos as $key => $aMemo)
                    @if ($aMemo->is_public === 1 || (Auth::user() && $aMemo->id_user === Auth::user()->id))
                        <li class="{{ $aMemo->is_public === 0 ? 'is_private' : '' }}">
                            <a href="{{ route('memos.show2', ['subDomain' => $data->domain, 'subCateg' => $data->slug, 'memo' => $aMemo->skey]) }}">
                                {{ $aMemo->title }}
                            </a>
                        </li>
                    @endif
                @endforeach
            </ul>

            @if (count($data->refs) > 0 || Auth::user())
                <div class="py-4">
                    <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                        <h3>Ressources disponibles</h3>
                        @auth
                            <a href="{{ route('references.create', ['id_memocateg' => $data->id]) }}" target="_blank"
                                rel="noopener noreferrer">Ajouter</a>
                        @endauth

                        @include('resources.references._listing', [
                            'references' => $data->refs,
                        ])
                    </div>
                </div>
            @endif
        </div>
    </div>
</x-app-layout>

resources/views/resources/memocategs/show.blade.php
<x-app-layout>
    <x-slot name="navigation">
        @include('layouts.navigation', [
            'menuContent' => $menuContent,
        ])
    </x-slot>

    <x-slot name="header">
        <h1 class="font-semibold text-xl leading-tight">
            {{ $categ->label }}
        </h1>
        @auth
            <a href="{{ route('memocategs.edit', $categ->slug) }}">Modifier</a>
        @endauth
    </x-slot>

    <div class="py-4">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            @if (count($categ->childrenCategs) > 0)
                <h2>Sous-catégories disponibles</h2>
                @foreach ($categ->childrenCategs as $aSubCateg)
                    @if (count($aSubCateg->memos) > 0)
                        <section class="py-2">
                            <h3><a href="{{ route('memocategs.show', $aSubCateg->slug) }}">{{ $aSubCateg->label }}</a>
                            </h3>
                            @if (count($aSubCateg->memos) > 0)
                                <ul>
                                    @foreach ($aSubCateg->memos as $aMemo)
                                        <li class="{{ $aMemo->is_public === 0 ? 'is_private' : '' }}"><a
                                                href="{{ route('memos.show2', ['subDomain' => $aMemo->domain, 'subCateg' => $aSubCateg->slug, 'memo' => $aMemo->skey]) }}">{{ $aMemo->title }}</a>
                                        </li>
                                    @endforeach
                                </ul>
                            @endif
                        </section>
                    @endif
                @endforeach
            @endif

            <section>
                <h2>Mémos associés</h2>
                @auth
                    <a href="{{ route('memos.create', ['id_memocateg' => $categ->id]) }}" target="_blank"
                        rel="noopener noreferrer">Ajouter</a>
                @endauth
                @if (count($categ->memos) > 0)

                    <ul>
                        @foreach ($categ->memos as $aMemo)
                            <li class="{{ $aMemo->is_public === 0 ? 'is_private' : '' }}"><a
                                    href="{{ route('memos.show2', ['subDomain' => $aMemo->domain, 'subCateg' => $categ->slug, 'memo' => $aMemo->skey]) }}">{{ $aMemo['title'] }}</a>
                            </li>
                        @endforeach
                    </ul>
                @endif
            </section>
        </div>
    </div>

    @if (count($categ->refs) > 0 || Auth::user())
        <div class="py-4">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
                <h2>Ressources disponibles</h2>
                @auth
                    <a href="{{ route('references.create', ['id_memocateg' => $categ->id]) }}" target="_blank"
                        rel="noopener noreferrer">Ajouter</a>
                @endauth

                @include('resources.references._listing', [
                    'references' => $categ->refs,
                ])
            </div>
        </div>
    @endif
</x-app-layout>